Edited Terminator URL to reflect new repo/maintainership and recent releases
k4m4/terminals-are-sexy pull request #275
Opened 2020-11-19 20:32 UTC by akierig

## Checklist for submitting a pull request to `Terminals Are Sexy`:

- [*x*] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/terminals-are-sexy/blob/master/contributing.md) of this repo.
- [*x*] I have **searched** the [PRs](https://github.com/k4m4/terminals-are-sexy/pulls) of this repo and believe that this is not a duplicate.

 

- **Terminator**: 
- **https://github.com/gnome-terminator/terminator**: 
- **Terminal Emulation Applications*: 
- **The Robot Future of Terminals*:

2020-11-21 17:56 UTC, k4m4 requested changes

2020-11-21 17:56 UTC, k4m4 commented on readme.md
> +* [Terminator](https://github.com/gnome-terminator/terminator) - The robot future of terminals.
Hey, thanks for your contribution! Could you also update the description to reflect the one on the new GitHub repo?

2020-12-03 22:30 UTC, akierig commented
Ope, yeah, it's done! sorry I'd missed that part.

2020-12-04 23:05 UTC, AboAlHur commented
HiHiمُرسل من هاتف Huawei الخاص بي-------- الرسالة الأصلية --------الموضوع: Re: [k4m4/terminals-are-sexy] Update Terminator URL (#275)من: akierig إلى: k4m4/terminals-are-sexy نسخة إلى: Subscribed 
Ope, yeah, it's done! sorry I'd missed that part.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-13 20:15 UTC, k4m4 approved these changes

2020-12-13 20:15 UTC, merged